name = "cf-workers-telegram-bot"
main = "packages/worker/dist/worker/src/worker.mjs"

workers_dev = true
compatibility_date = "2023-10-24"

build.command = "npm install && npm run build:worker"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "telebot"
database_id = "6f7efc7b-e163-4d11-a21e-6d6d8ff289db"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"
